"use client";
import { useCallback,useEffect,useMemo,useState,type FormEvent } from "react";
import Link from "next/link";
import type { GovernanceWorkspaceDTO, MeetingLifecycleMilestoneDTO } from "@/lib/governance-types";
import { formatBusinessMoment, temporalZoneNote, toDateTimeLocal } from "@/lib/temporal";
import { Icon } from "./Icon";
import { MeetingLifecyclePanel } from "./MeetingLifecyclePanel";
import { useTemporalPreferences } from "./TemporalContext";

const statusLabels:Record<string,string>={draft:"Borrador",called:"Convocada",in_progress:"En curso",review:"Acta en revisión",closed:"Cerrada",
 pending:"Pendiente",open:"Votación abierta",approved:"Aprobado",rejected:"Rechazado",tied:"Empate",present:"Presente",represented:"Representada",absent:"Ausente",
 simple_majority:"Mayoría simple",qualified_majority:"Mayoría cualificada",unanimity:"Unanimidad"};
export function GovernanceWorkspace({canWrite}:{canWrite:boolean}){
 const preferences=useTemporalPreferences();
 const[data,setData]=useState<GovernanceWorkspaceDTO|null>(null),[selected,setSelected]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const[agendaOpen,setAgendaOpen]=useState(false),[title,setTitle]=useState(""),[proposal,setProposal]=useState(""),[rule,setRule]=useState("simple_majority"),[threshold,setThreshold]=useState("66.67");
 const[agreementItem,setAgreementItem]=useState(""),[responsible,setResponsible]=useState(""),[dueDate,setDueDate]=useState("");
 const[profileOpen,setProfileOpen]=useState(false),[convenerName,setConvenerName]=useState(""),[sessionCall,setSessionCall]=useState("first"),[secondCallAt,setSecondCallAt]=useState("");
 const[milestone,setMilestone]=useState<MeetingLifecycleMilestoneDTO|null>(null),[milestoneAt,setMilestoneAt]=useState(""),[evidenceReference,setEvidenceReference]=useState(""),[milestoneNote,setMilestoneNote]=useState("");
 const load=useCallback(async(id?:string)=>{setError("");try{const response=await fetch("/api/governance/dashboard"+(id?"?meetingId="+id:""),{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error||"No se pudo cargar.");setData(result);setSelected(result.selected?.id||"");}catch(e){setError(e instanceof Error?e.message:"No se pudo cargar.");}},[]);
 useEffect(()=>{const t=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(t);},[load]);
 useEffect(()=>{if(!message)return;const t=window.setTimeout(()=>setMessage(""),4500);return()=>window.clearTimeout(t);},[message]);
 const current=data?.selected;
 const votesByItem=useMemo(()=>new Map((data?.agenda||[]).map(item=>[item.id,(data?.votes||[]).filter(v=>v.agendaItemId===item.id)])),[data]);
 async function mutate(url:string,method="POST",body?:unknown,success="Cambios guardados."){
  setBusy(true);setError("");try{const response=await fetch(url,{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error||"No se pudo completar.");setMessage(success);await load(selected);return true;}catch(e){setError(e instanceof Error?e.message:"No se pudo completar.");return false;}finally{setBusy(false);}
 }
 async function addAgenda(e:FormEvent){e.preventDefault();if(await mutate("/api/governance/meetings/"+selected+"/agenda","POST",{title,proposal,votingRule:rule,qualifiedThreshold:Number(threshold)},"Punto añadido al orden del día.")){setAgendaOpen(false);setTitle("");setProposal("");}}
 function openProfile(){if(!data?.lifecycle)return;setConvenerName(data.lifecycle.configuration.convenerName);setSessionCall(data.lifecycle.configuration.sessionCall);setSecondCallAt(toDateTimeLocal(data.lifecycle.configuration.secondCallAt,preferences));setProfileOpen(true);}
 function openMilestone(item:MeetingLifecycleMilestoneDTO){setMilestone(item);setMilestoneAt(toDateTimeLocal(item.completedAt??new Date(),preferences));setEvidenceReference(item.version&&item.evidenceReference?item.evidenceReference:"");setMilestoneNote(item.note??"");}
 async function saveProfile(e:FormEvent){e.preventDefault();if(!current)return;if(await mutate("/api/governance/meetings/"+selected+"/legal-profile","PATCH",{convenerName,sessionCall,secondCallAt:sessionCall==="second"?secondCallAt:null,version:current.version},"Datos legales de la junta actualizados."))setProfileOpen(false);}
 async function saveMilestone(e:FormEvent){e.preventDefault();if(!milestone?.actionKey)return;if(await mutate("/api/governance/meetings/"+selected+"/milestones/"+milestone.actionKey,"PUT",{occurredAt:milestoneAt,evidenceReference,note:milestoneNote,version:milestone.version},"Hito registrado con fecha, hora y evidencia."))setMilestone(null);}
 if(!data)return <div className="page governance-workspace">{error?<div className="form-alert">{error}</div>:<div className="finance-loading"><span className="spinner"/> Cargando juntas…</div>}</div>;
 return <div className="page governance-workspace">
  <div className="module-breadcrumb"><Link href="/inicio">← Inicio</Link><span>/</span><span>Gobierno</span></div>
  <header className="page-heading"><div><span className="eyebrow">GOBIERNO TRAZABLE</span><h1>Juntas y acuerdos</h1><p>Convocatoria, asistencia, votación y ejecución de acuerdos en un único expediente.</p></div><div className="heading-actions"><Link className="button button-secondary" href="/juntas?view=records">Gestionar fichas</Link>{canWrite&&current&&<button className="button button-primary" onClick={()=>setAgendaOpen(true)}><Icon name="plus" size={18}/> Añadir punto</button>}</div></header>
  {error&&<div className="form-alert" role="alert">{error}</div>}
  <section className="governance-selector"><label>Junta<select value={selected} onChange={e=>void load(e.target.value)}>{data.meetings.map(m=><option value={m.id} key={m.id}>{m.title} · {statusLabels[m.status]||m.status}</option>)}</select></label>{current&&<div><span className={"finance-status status-"+current.status}>{statusLabels[current.status]||current.status}</span><strong>{current.eventDate?`Celebración: ${formatBusinessMoment(current.eventDate,current.eventTimePrecision,preferences)}`:"Sin fecha de celebración"}</strong><small>{current.location||current.code} · {temporalZoneNote(preferences)}</small></div>}</section>
  {!current?<div className="empty-state"><h2>Todavía no hay juntas</h2><p>Crea la primera ficha desde la gestión de juntas.</p></div>:<>
   {data.lifecycle&&<MeetingLifecyclePanel lifecycle={data.lifecycle} canWrite={canWrite} onEditProfile={openProfile} onEditMilestone={openMilestone}/>}
   <section className="governance-metrics"><article><small>Unidades representadas</small><strong>{data.quorum.units}</strong></article><article><small>Coeficiente representado</small><strong>{data.quorum.coefficient.toFixed(3)} %</strong></article><article><small>Puntos del orden</small><strong>{data.agenda.length}</strong></article><article><small>Acuerdos en seguimiento</small><strong>{data.agreements.filter(a=>a.status!=="completed").length}</strong></article></section>
   <div className="governance-grid"><section className="governance-panel attendance-panel"><header><div><span className="section-chip">ASISTENCIA</span><h2>Unidades y representación</h2></div>{canWrite&&<button className="button button-secondary" disabled={busy} onClick={()=>void mutate("/api/governance/meetings/"+selected+"/attendance","POST",undefined,"Censo de asistencia preparado.")}>Preparar censo</button>}</header><div className="attendance-list">{data.attendance.map(row=><label key={row.id}><span><strong>{row.unitCode} · {row.ownerName}</strong><small>Coeficiente {row.coefficient.toFixed(3)} %</small></span><select disabled={!canWrite||busy} value={row.attendanceType} onChange={e=>void mutate("/api/governance/meetings/"+selected+"/attendance","PATCH",{unitId:row.unitId,attendanceType:e.target.value},"Asistencia actualizada.")}><option value="absent">Ausente</option><option value="present">Presente</option><option value="represented">Representada</option></select></label>)}</div></section>
    <section className="governance-panel agenda-panel"><header><div><span className="section-chip">ORDEN DEL DÍA</span><h2>Debate y votación</h2></div></header><div className="agenda-list">{data.agenda.map(item=>{const votes=votesByItem.get(item.id)||[];const agreement=data.agreements.find(a=>a.agendaItemId===item.id);return <article key={item.id}><header><span>{item.position}</span><div><h3>{item.title}</h3><small>{statusLabels[item.votingRule]||item.votingRule}</small></div><b className={"finance-status status-"+item.status}>{statusLabels[item.status]||item.status}</b></header><p>{item.proposal}</p><div className="vote-totals"><span>Sí <strong>{votes.filter(v=>v.choice==="yes").length}</strong></span><span>No <strong>{votes.filter(v=>v.choice==="no").length}</strong></span><span>Abstención <strong>{votes.filter(v=>v.choice==="abstain").length}</strong></span></div>{canWrite&&data.attendance.filter(a=>a.attendanceType!=="absent").map(a=><label className="unit-vote" key={a.unitId}><span>{a.unitCode}</span><select value={votes.find(v=>v.unitId===a.unitId)?.choice||""} onChange={e=>void mutate("/api/governance/votes","POST",{agendaItemId:item.id,unitId:a.unitId,choice:e.target.value},"Voto registrado y resultado recalculado.")}><option value="" disabled>Registrar voto</option><option value="yes">Sí</option><option value="no">No</option><option value="abstain">Abstención</option></select></label>)}{item.status==="approved"&&!agreement&&canWrite&&<button className="button button-primary agreement-button" onClick={()=>{setAgreementItem(item.id);setTitle(item.title);}}>Crear acuerdo y responsable</button>}{agreement&&<div className="agreement-card"><Icon name="badge-check" size={18}/><span><strong>{agreement.title}</strong><small>{agreement.responsible}{agreement.dueDate?` · Fecha objetivo: ${formatBusinessMoment(agreement.dueDate,agreement.dueTimePrecision,preferences,{deadline:true,inclusive:agreement.dueInclusive})}`:" · Sin fecha objetivo"}</small></span></div>}</article>})}</div></section></div>
   {canWrite&&<div className="governance-close"><Icon name="shield-check" size={21}/><div><strong>El cierre ya forma parte del ciclo</strong><small>La junta se marcará como cerrada al registrar el acta firmada, después de completar asistencia, resultados y acuerdos.</small></div></div>}
  </>}
  {agendaOpen&&<div className="modal-backdrop"><section className="record-dialog governance-dialog" role="dialog" aria-modal="true"><header className="dialog-header"><div><span className="eyebrow">NUEVO PUNTO</span><h2>Orden del día</h2></div><button className="icon-button" onClick={()=>setAgendaOpen(false)}><Icon name="close"/></button></header><form onSubmit={addAgenda} className="dialog-form"><div className="dialog-scroll form-grid"><label className="field-group field-wide">Título<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label className="field-group field-wide">Propuesta<textarea value={proposal} onChange={e=>setProposal(e.target.value)} rows={4} required/></label><label className="field-group">Regla<select value={rule} onChange={e=>setRule(e.target.value)}><option value="simple_majority">Mayoría simple</option><option value="qualified_majority">Mayoría cualificada</option><option value="unanimity">Unanimidad</option></select></label>{rule==="qualified_majority"&&<label className="field-group">Umbral (%)<input type="number" min="50" max="100" step=".01" value={threshold} onChange={e=>setThreshold(e.target.value)}/></label>}</div><footer className="dialog-footer"><span/><div className="dialog-footer-actions"><button type="button" className="button button-secondary" onClick={()=>setAgendaOpen(false)}>Cancelar</button><button className="button button-primary" disabled={busy}>Añadir punto</button></div></footer></form></section></div>}
  {agreementItem&&<div className="modal-backdrop"><section className="record-dialog governance-dialog" role="dialog" aria-modal="true"><header className="dialog-header"><div><span className="eyebrow">ACUERDO EJECUTABLE</span><h2>{title}</h2></div><button className="icon-button" onClick={()=>setAgreementItem("")}><Icon name="close"/></button></header><div className="dialog-scroll form-grid"><label className="field-group field-wide">Descripción<textarea value={proposal} onChange={e=>setProposal(e.target.value)} rows={4}/></label><label className="field-group">Responsable<input value={responsible} onChange={e=>setResponsible(e.target.value)}/></label><label className="field-group">Fecha y hora objetivo (incluida)<input type="datetime-local" step="1" value={dueDate} onChange={e=>setDueDate(e.target.value)}/><small className="field-hint">Se admite actuar hasta ese segundo. {temporalZoneNote(preferences)}.</small></label></div><footer className="dialog-footer"><span/><div className="dialog-footer-actions"><button className="button button-secondary" onClick={()=>setAgreementItem("")}>Cancelar</button><button className="button button-primary" disabled={busy} onClick={async()=>{await mutate("/api/governance/meetings/"+selected+"/agreements","POST",{agendaItemId:agreementItem,title,description:proposal,responsible,dueDate},"Acuerdo creado con responsable.");setAgreementItem("");}}>Guardar acuerdo</button></div></footer></section></div>}
  {profileOpen&&<div className="modal-backdrop"><section className="record-dialog governance-dialog" role="dialog" aria-modal="true" aria-labelledby="legal-profile-title"><header className="dialog-header"><div><span className="eyebrow">DATOS LEGALES</span><h2 id="legal-profile-title">Configuración de la junta</h2><p>Estos datos alimentan el ciclo y el contenido mínimo del acta.</p></div><button className="icon-button" type="button" onClick={()=>setProfileOpen(false)}><Icon name="close"/></button></header><form className="dialog-form" onSubmit={saveProfile}><div className="dialog-scroll form-grid"><label className="field-group field-wide">Autor de la convocatoria<input value={convenerName} onChange={e=>setConvenerName(e.target.value)} placeholder="Presidencia o propietarios promotores" required/></label><label className="field-group">Celebración<select value={sessionCall} onChange={e=>setSessionCall(e.target.value)}><option value="first">Primera convocatoria</option><option value="second">Segunda convocatoria</option><option value="universal">Junta universal</option></select></label>{sessionCall==="second"&&<label className="field-group">Fecha y hora de segunda convocatoria<input type="datetime-local" step="1" value={secondCallAt} onChange={e=>setSecondCallAt(e.target.value)} required/><small className="field-hint">Al menos 30 minutos después de la primera si es el mismo día. {temporalZoneNote(preferences)}.</small></label>}<aside className="readonly-record-note field-wide"><Icon name="info" size={18}/><span><strong>Junta universal</strong><small>Úsala solo si concurre la totalidad de propietarios y todos deciden reunirse sin convocatoria previa.</small></span></aside></div><footer className="dialog-footer"><span/><div className="dialog-footer-actions"><button className="button button-secondary" type="button" onClick={()=>setProfileOpen(false)}>Cancelar</button><button className="button button-primary" disabled={busy}>Guardar datos legales</button></div></footer></form></section></div>}
  {milestone&&<div className="modal-backdrop"><section className="record-dialog governance-dialog" role="dialog" aria-modal="true" aria-labelledby="milestone-title"><header className="dialog-header"><div><span className="eyebrow">EVIDENCIA DEL EXPEDIENTE</span><h2 id="milestone-title">{milestone.title}</h2><p>{milestone.legalSource}</p></div><button className="icon-button" type="button" onClick={()=>setMilestone(null)}><Icon name="close"/></button></header><form className="dialog-form" onSubmit={saveMilestone}><div className="dialog-scroll form-grid"><label className="field-group">Fecha y hora reales<input type="datetime-local" step="1" value={milestoneAt} onChange={e=>setMilestoneAt(e.target.value)} required/><small className="field-hint">{temporalZoneNote(preferences)}. No se aceptan hitos sin hora.</small></label><label className="field-group">Referencia de evidencia<input value={evidenceReference} onChange={e=>setEvidenceReference(e.target.value)} placeholder="Ej.: DOC-2026-018 / acuse de entrega" minLength={2} maxLength={200} required/></label><label className="field-group field-wide">Observación<textarea value={milestoneNote} onChange={e=>setMilestoneNote(e.target.value)} rows={4} maxLength={1000} placeholder="Canal, firmantes, incidencias o criterio aplicado"/></label><aside className="readonly-record-note field-wide"><Icon name="shield-check" size={18}/><span><strong>Registro auditado</strong><small>Se conservarán quién confirmó el hito, su fecha y hora, la evidencia indicada y las correcciones posteriores.</small></span></aside></div><footer className="dialog-footer"><span/><div className="dialog-footer-actions"><button className="button button-secondary" type="button" onClick={()=>setMilestone(null)}>Cancelar</button><button className="button button-primary" disabled={busy}>{milestone.version?"Guardar corrección":"Registrar hito"}</button></div></footer></form></section></div>}
  {message&&<div className="toast" role="status"><Icon name="badge-check" size={18}/>{message}</div>}
 </div>;
}
