import {
  Activity,
  AlertTriangle,
  ArrowUpDown,
  ArrowRight,
  BadgeCheck,
  Bell,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  CalendarCheck2,
  ChevronDown,
  CircleHelp,
  ClipboardCheck,
  Cloud,
  CloudLightning,
  CloudRain,
  CloudSun,
  Download,
  Droplets,
  FileArchive,
  Files,
  GripVertical,
  HardHat,
  Home,
  Info,
  Landmark,
  LayoutDashboard,
  LogOut,
  Maximize2,
  Megaphone,
  Menu,
  Minimize2,
  Moon,
  MoreHorizontal,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  RotateCcw,
  ScrollText,
  Search,
  Settings,
  SlidersHorizontal,
  ShieldCheck,
  Snowflake,
  Sparkles,
  Sun,
  Trash2,
  Upload,
  Users,
  Vote,
  WalletCards,
  Wrench,
  X,
  Zap,
  type LucideProps
} from "lucide-react";

const icons = {
  activity: Activity,
  "alert-triangle": AlertTriangle,
  "arrow-up-down": ArrowUpDown,
  "arrow-right": ArrowRight,
  "badge-check": BadgeCheck,
  bell: Bell,
  book: BookOpen,
  briefcase: BriefcaseBusiness,
  building: Building2,
  "calendar-check": CalendarCheck2,
  "chevron-down": ChevronDown,
  help: CircleHelp,
  approval: ClipboardCheck,
  cloud: Cloud,
  "cloud-lightning": CloudLightning,
  "cloud-rain": CloudRain,
  "cloud-sun": CloudSun,
  download: Download,
  droplets: Droplets,
  archive: FileArchive,
  files: Files,
  grip: GripVertical,
  "hard-hat": HardHat,
  home: Home,
  info: Info,
  landmark: Landmark,
  dashboard: LayoutDashboard,
  logout: LogOut,
  maximize: Maximize2,
  megaphone: Megaphone,
  menu: Menu,
  minimize: Minimize2,
  moon: Moon,
  more: MoreHorizontal,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  "refresh-cw": RefreshCw,
  undo: RotateCcw,
  "scroll-text": ScrollText,
  search: Search,
  settings: Settings,
  filter: SlidersHorizontal,
  "shield-check": ShieldCheck,
  snowflake: Snowflake,
  sparkles: Sparkles,
  sun: Sun,
  trash: Trash2,
  upload: Upload,
  users: Users,
  vote: Vote,
  wallet: WalletCards,
  wrench: Wrench,
  zap: Zap,
  close: X
} as const;

export type IconName = keyof typeof icons;

export function Icon({ name, ...props }: LucideProps & { name: IconName | string }) {
  const Component = icons[name as IconName] ?? Sparkles;
  return <Component aria-hidden="true" {...props} />;
}
